# frozen_string_literal: true

source 'http://rubygems.org'

gem 'ffi'
gem 'capybara'
gem 'cucumber'
gem 'rake'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'rspec'
gem 'syntax'
gem 'poltergeist'
gem 'rubocop'
gem 'faker'